HubAsset:
  Type: "EdgeConnectorForKVSHubAsset"
  Name: "DunhillOrindaSqGarAHub"
  HubName: "DunhillOrindaSqGarAHub"
  ChildrenCameraSiteWiseAssetName: ["DunhillOrindaSqGarCameraAssetA"]

CameraAsset:
  Type: "EdgeConnectorForKVSCameraAsset"
  Name: "DunhillOrindaSqGarCameraAssetA"
  CaptureStartTime: "* * * * *"
  CaptureDurationInMinutes: 10
  LocalDataRetentionPeriodInMinutes: 60
  KinesisVideoStreamName: "dunhill-ornd_sq_gar-stream-a"
  LiveStreamingStartTime: "* * * * *"
  LiveStreamingDurationInMinutes: 10
  RTSPStream: rtsp://admin:admin1357@172.16.55.194:554/cam/realmonitor?channel=1&subtype=0
