HubAsset:
  Type: "EdgeConnectorForKVSHubAsset"
  Name: "McCordDevRedemptionSqGarBHub"
  HubName: "McCordDevRedemptionSqGarBHub"
  ChildrenCameraSiteWiseAssetName: ["McCordDevRedemptionSqGarBCameraAssetA", "McCordDevRedemptionSqGarBCameraAssetB"]

CameraAsset1:
  Type: "EdgeConnectorForKVSCameraAsset"
  Name: "McCordDevRedemptionSqGarBCameraAssetA"
  CaptureStartTime: "* * * * *"
  CaptureDurationInMinutes: 10
  LocalDataRetentionPeriodInMinutes: 60
  KinesisVideoStreamName: "mccorddev-redemption_sq_gar-b-stream-a"
  LiveStreamingStartTime: "* * * * *"
  LiveStreamingDurationInMinutes: 10
  RTSPStream: rtsp://admin:admin1357@172.16.60.197:554/cam/realmonitor?channel=1&subtype=0

CameraAsset2:
  Type: "EdgeConnectorForKVSCameraAsset"
  Name: "McCordDevRedemptionSqGarBCameraAssetB"
  CaptureStartTime: "* * * * *"
  CaptureDurationInMinutes: 10
  LocalDataRetentionPeriodInMinutes: 60
  KinesisVideoStreamName: "mccorddev-redemption_sq_gar-b-stream-b"
  LiveStreamingStartTime: "* * * * *"
  LiveStreamingDurationInMinutes: 10
  RTSPStream: rtsp://admin:admin1357@172.16.60.198:554/cam/realmonitor?channel=1&subtype=0